groups:
  - name: resource-alerts
    rules:
      - alert: HighCPUUsage
        expr: container_cpu_usage_seconds_total{container="alertmanager"} > 0.5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected in container {{ $labels.container }}"
          description: "CPU usage is above 50% for 1 minute."

      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes{container="alertmanager"} > 100000000
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage detected in container {{ $labels.container }}"
          description: "Memory usage is above 100MB for 1 minute."

